FROM node:22-bookworm

WORKDIR /workspace
# COPY .devcontainer/fonts.conf /etc/fonts/local.conf

RUN apt-get update -y \
  # && apt-get upgrade -y \
  && apt-get install -y --no-install-recommends \
  sudo \
  && apt-get -y clean \
  && rm -rf /var/lib/apt/lists/* \
  && echo 'node:node' | chpasswd \
  && gpasswd -a node sudo

USER node
