/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  "/health": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
        /** ヘルスチェック */
    get: {
      parameters: {
        query?: never;
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody?: never;
      responses: {
                /** @description ヘルスチェック */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": {
              now: number;
            };
          };
        };
                /** @description null */
        404: {
          headers: {
            [name: string]: unknown;
          };
          content?: never;
        };
      };
    };
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/sandbox/api": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
        /** 一覧の取得 */
    get: {
      parameters: {
        query?: {
                    /** @description １ページあたりの件数 */
          limit?: number;
                    /** @description ページ番号 */
          page?: number;
        };
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody?: never;
      responses: {
                /** @description 一覧 */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": {
                            /** @example 1 */
              page: number;
                            /** @example 100 */
              total: number;
              items: components["schemas"]["Sandbox"][];
            };
          };
        };
      };
    };
    put?: never;
        /** 詳細作成 */
    post: {
      parameters: {
        query?: never;
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody: {
        content: {
          "application/json": components["schemas"]["NewSandBox"];
        };
      };
      responses: {
                /** @description 作成成功 */
        201: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": components["schemas"]["Sandbox"];
          };
        };
      };
    };
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/sandbox/api/{id}": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
        /** 詳細取得 */
    get: {
      parameters: {
        query?: never;
        header?: never;
        path: {
          id: number;
        };
        cookie?: never;
      };
      requestBody?: never;
      responses: {
                /** @description 詳細 */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": components["schemas"]["Sandbox"];
          };
        };
                /** @description ダミー */
        201: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": components["schemas"]["NewSandBox"];
          };
        };
                /** @description 見つかりません */
        404: {
          headers: {
            [name: string]: unknown;
          };
          content?: never;
        };
      };
    };
        /** 更新 */
    put: {
      parameters: {
        query?: never;
        header?: never;
        path: {
          id: number;
        };
        cookie?: never;
      };
      requestBody: {
        content: {
          "application/json": components["schemas"]["Sandbox"];
        };
      };
      responses: {
                /** @description 詳細 */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": components["schemas"]["Sandbox"];
          };
        };
      };
    };
    post?: never;
        /** 削除 */
    delete: {
      parameters: {
        query?: never;
        header?: never;
        path: {
          id: number;
        };
        cookie?: never;
      };
      requestBody?: never;
      responses: {
                /** @description 削除成功 */
        204: {
          headers: {
            [name: string]: unknown;
          };
          content?: never;
        };
      };
    };
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
}
export type webhooks = Record<string, never>;
export interface components {
  schemas: {
    Sandbox: {
      id: number;
      title: string;
      body: string;
      updated_at: string;
    };
    NewSandBox: {
      title: string;
      body: string;
    };
  };
  responses: never;
  parameters: never;
  requestBodies: never;
  headers: never;
  pathItems: never;
}
export type $defs = Record<string, never>;
export type operations = Record<string, never>;
