openapi: "3.1.0"
info:
  title: "internal API"
  description: "internal API"
  version: "0.0.0"
servers:
  - url: "http://localhost:3000"
paths:
  /health:
    summary: ""
    get:
      summary: "ヘルスチェック"
      responses:
        "200":
          description: ""
          content:
            application/json:
              schema:
                type: "object"
                properties:
                  now:
                    type: "string"
                    example: "2025-01-01T00:00:00.000Z"
  /sandbox/api:
    summary: ""
    get:
      summary: "一覧の取得"
      parameters:
        - name: "limit"
          in: "query"
          required: false
          schema:
            type: "integer"
            default: 10
            example: 1
        - name: "page"
          in: "query"
          required: false
          schema:
            type: "integer"
            default: 1
            example: 1
      responses:
        "200":
          description: "一覧取得成功"
          content:
            application/json:
              schema:
                type: "object"
                properties:
                  page:
                    type: "integer"
                    default: 1
                    example: 1
                  total:
                    type: "integer"
                    example: 100
                  items:
                    type: "array"
                    items:
                      type: "object"
                      properties:
                        id:
                          type: "string"
                          example: "abc123"
                        title:
                          type: "string"
                          example: "title"
                        body:
                          type: "string"
                          example: "body"
                        updatedAt:
                          type: "string"
                          example: "2025-01-01T00:00:00.000Z"
                      required:
                        - "id"
                        - "title"
                        - "body"
                        - "updatedAt"
                required:
                  - "page"
                  - "total"
                  - "items"
    post:
      summary: "詳細作成"
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: "object"
              properties:
                title:
                  type: "string"
                  example: "title"
                body:
                  type: "string"
                  example: "body"
                updatedAt:
                  type: "string"
                  example: "2025-01-01T00:00:00.000Z"
              required:
                - "title"
                - "body"
                - "updatedAt"
      responses:
        "201":
          description: "作成成功"
          content:
            application/json:
              schema:
                type: "object"
                properties:
                  id:
                    type: "string"
                    example: "abc123"
                  title:
                    type: "string"
                    example: "title"
                  body:
                    type: "string"
                    example: "body"
                  updatedAt:
                    type: "string"
                    example: "2025-01-01T00:00:00.000Z"
                required:
                  - "id"
                  - "title"
                  - "body"
                  - "updatedAt"
  /sandbox/api/{id}:
    summary: ""
    get:
      summary: "詳細取得"
      responses:
        "200":
          description: "詳細取得成功"
          content:
            application/json:
              schema:
                type: "object"
                properties:
                  id:
                    type: "string"
                    example: "abc123"
                  title:
                    type: "string"
                    example: "title"
                  body:
                    type: "string"
                    example: "body"
                  updatedAt:
                    type: "string"
                    example: "2025-01-01T00:00:00.000Z"
                required:
                  - "id"
                  - "title"
                  - "body"
                  - "updatedAt"
        "404":
          description: "詳細取得失敗"
    put:
      summary: "詳細更新"
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: "object"
              properties:
                title:
                  type: "string"
                  example: "title"
                body:
                  type: "string"
                  example: "body"
                updatedAt:
                  type: "string"
                  example: "2025-01-01T00:00:00.000Z"
              required:
                - "title"
                - "body"
                - "updatedAt"
      responses:
        "201":
          description: "詳細更新成功"
          content:
            application/json:
              schema:
                type: "object"
                properties:
                  id:
                    type: "string"
                    example: "abc123"
                  title:
                    type: "string"
                    example: "title"
                  body:
                    type: "string"
                    example: "body"
                  updatedAt:
                    type: "string"
                    example: "2025-01-01T00:00:00.000Z"
                required:
                  - "id"
                  - "title"
                  - "body"
                  - "updatedAt"
    delete:
      summary: "詳細削除"
      responses:
        "204":
          description: "削除成功"
